/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asignacion.vista;

/**
 *
 * @author javi2
 */
public class HabilitacionCursos extends javax.swing.JFrame {

    /**
     * Creates new form HabilitacionCursos
     */
    public HabilitacionCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Pnl_Habilitarcursos = new javax.swing.JPanel();
        Lbl_hablilitacion = new javax.swing.JLabel();
        Lbl_idcurso = new javax.swing.JLabel();
        Lbl_nombre = new javax.swing.JLabel();
        Lbl_estatus = new javax.swing.JLabel();
        Txt_idcurso = new javax.swing.JTextField();
        Txt_nombre = new javax.swing.JTextField();
        Cbo_estatus = new javax.swing.JComboBox<>();
        Btn_guardar = new javax.swing.JButton();
        Btn_ayuda = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();
        Btn_salir = new javax.swing.JButton();

        jLabel4.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lbl_hablilitacion.setBackground(java.awt.SystemColor.controlLtHighlight);
        Lbl_hablilitacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Lbl_hablilitacion.setText("Habilitacion de Cursos");

        Lbl_idcurso.setBackground(java.awt.SystemColor.controlLtHighlight);
        Lbl_idcurso.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Lbl_idcurso.setText("Id Curso");

        Lbl_nombre.setBackground(java.awt.SystemColor.controlLtHighlight);
        Lbl_nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Lbl_nombre.setText("Nombre");

        Lbl_estatus.setBackground(java.awt.SystemColor.controlLtHighlight);
        Lbl_estatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Lbl_estatus.setText("Estatus");

        Cbo_estatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Cbo_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        Cbo_estatus.setPreferredSize(new java.awt.Dimension(85, 38));

        Btn_guardar.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_guardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_guardar.setText("Guardar");
        Btn_guardar.setPreferredSize(new java.awt.Dimension(85, 38));

        Btn_ayuda.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_ayuda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_ayuda.setText("Ayuda");
        Btn_ayuda.setPreferredSize(new java.awt.Dimension(85, 38));

        Btn_buscar.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_buscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_buscar.setText("Buscar");
        Btn_buscar.setPreferredSize(new java.awt.Dimension(85, 38));

        Btn_salir.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_salir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_salir.setText("Salir");
        Btn_salir.setPreferredSize(new java.awt.Dimension(85, 38));

        javax.swing.GroupLayout Pnl_HabilitarcursosLayout = new javax.swing.GroupLayout(Pnl_Habilitarcursos);
        Pnl_Habilitarcursos.setLayout(Pnl_HabilitarcursosLayout);
        Pnl_HabilitarcursosLayout.setHorizontalGroup(
            Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_HabilitarcursosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_HabilitarcursosLayout.createSequentialGroup()
                        .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_HabilitarcursosLayout.createSequentialGroup()
                                .addComponent(Lbl_idcurso)
                                .addGap(14, 14, 14)
                                .addComponent(Txt_idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_estatus))
                        .addGap(29, 29, 29)
                        .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl_HabilitarcursosLayout.createSequentialGroup()
                                .addComponent(Btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_HabilitarcursosLayout.createSequentialGroup()
                                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cbo_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(Lbl_nombre)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(Pnl_HabilitarcursosLayout.createSequentialGroup()
                        .addComponent(Lbl_hablilitacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        Pnl_HabilitarcursosLayout.setVerticalGroup(
            Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_HabilitarcursosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_hablilitacion)
                    .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_idcurso)
                    .addComponent(Lbl_nombre)
                    .addComponent(Txt_idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbo_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_estatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(Pnl_HabilitarcursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Habilitarcursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_Habilitarcursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabilitacionCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabilitacionCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabilitacionCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabilitacionCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabilitacionCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JButton Btn_salir;
    private javax.swing.JComboBox<String> Cbo_estatus;
    private javax.swing.JLabel Lbl_estatus;
    private javax.swing.JLabel Lbl_hablilitacion;
    private javax.swing.JLabel Lbl_idcurso;
    private javax.swing.JLabel Lbl_nombre;
    private javax.swing.JPanel Pnl_Habilitarcursos;
    private javax.swing.JTextField Txt_idcurso;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
