
package asignacion.vista;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import asignacion.datos.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class ListadoAlumnosSeccion extends javax.swing.JFrame {

    Conexion enlace = new Conexion();
    Connection conect = enlace.conectar();
    
        
    public ListadoAlumnosSeccion() {
        initComponents();
        mostrarlistado(null,null);
    }
    
    /**
     *
     * @param curso
     * @param seccion
     */
    public void mostrarlistado(String curso, String seccion){
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Id Asignacion");
    modelo.addColumn("Id Curso");
    modelo.addColumn("Id Alumno");
    modelo.addColumn("Nombres");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Seccion");
    modelo.addColumn("Fecha");
    Tbl_listadoalumnosseccion.setModel(modelo);
    
    String codsql = null;
    String cont;
    cont = "SELECT COUNT(idCurso) FROM cursos where idCurso   = '"+txt_idcurso+"'";
    Connection cn = null;
    
    ResultSet rs = null;
    
   ;
    
    try{
    if(Integer.parseInt(cont)== 1){
       
        codsql = "SELECT A.idAsinacion, B.idCurso, C.idAlumno, C.nombres, C.apellidos, A.fecha, B.seccion FROM asignacionalumno A INNER JOIN cursos B INNER JOIN alumno C WHERE idCurso= '"+curso+"', seccion='"+seccion+"'";
    }
    }catch (NumberFormatException nfe){
        JOptionPane.showMessageDialog(null, nfe);
    }
    return cont;
    
    
    String []datos = new String[7];
    
    try{
        java.sql.Statement leer =  conect.createStatement();
        ResultSet resultado = leer.executeQuery(codsql);
        
        while(resultado.next()){
            datos[0] = resultado.getString(1);
            datos[1] = resultado.getString(2);
            datos[2] = resultado.getString(3);
            datos[3] = resultado.getString(4);
            datos[4] = resultado.getString(5);
            datos[5] = resultado.getString(6);
            datos[6] = resultado.getString(7);
            modelo.addRow(datos);
        }
        Tbl_listadoalumnosseccion.setModel(modelo);
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e + "Error en la consulta");
    
    }
    
     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_ListadoAlumnosSeccion = new javax.swing.JPanel();
        lbl_listado = new javax.swing.JLabel();
        Lbl_idcurso = new javax.swing.JLabel();
        txt_idcurso = new javax.swing.JTextField();
        Lbl_seccion = new javax.swing.JLabel();
        txt_idseccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_listadoalumnosseccion = new javax.swing.JTable();
        Btn_buscar = new javax.swing.JButton();
        Btn_salir = new javax.swing.JButton();
        Btn_ayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_listado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_listado.setText("Listado de Alumnos por Sección");

        Lbl_idcurso.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Lbl_idcurso.setText("Id Curso");

        txt_idcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idcursoActionPerformed(evt);
            }
        });

        Lbl_seccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Lbl_seccion.setText("Seccion");

        txt_idseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idseccionActionPerformed(evt);
            }
        });

        Tbl_listadoalumnosseccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tbl_listadoalumnosseccion);

        Btn_buscar.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_buscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_buscar.setText("Buscar");
        Btn_buscar.setPreferredSize(new java.awt.Dimension(85, 38));
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        Btn_salir.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_salir.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_salir.setText("Salir");
        Btn_salir.setPreferredSize(new java.awt.Dimension(85, 38));

        Btn_ayuda.setBackground(java.awt.SystemColor.controlLtHighlight);
        Btn_ayuda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_ayuda.setText("Ayuda");
        Btn_ayuda.setPreferredSize(new java.awt.Dimension(85, 38));

        javax.swing.GroupLayout Pnl_ListadoAlumnosSeccionLayout = new javax.swing.GroupLayout(Pnl_ListadoAlumnosSeccion);
        Pnl_ListadoAlumnosSeccion.setLayout(Pnl_ListadoAlumnosSeccionLayout);
        Pnl_ListadoAlumnosSeccionLayout.setHorizontalGroup(
            Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                        .addGroup(Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                                .addComponent(Lbl_idcurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addComponent(lbl_listado))
                        .addComponent(Lbl_seccion)
                        .addGap(18, 18, 18)
                        .addComponent(txt_idseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Pnl_ListadoAlumnosSeccionLayout.setVerticalGroup(
            Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                        .addComponent(lbl_listado)
                        .addGap(48, 48, 48)
                        .addGroup(Pnl_ListadoAlumnosSeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_idcurso)
                            .addComponent(txt_idcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_seccion)
                            .addComponent(txt_idseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_ListadoAlumnosSeccionLayout.createSequentialGroup()
                        .addComponent(Btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pnl_ListadoAlumnosSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pnl_ListadoAlumnosSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idcursoActionPerformed

    private void txt_idseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idseccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idseccionActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
            String curso = txt_idcurso.getText();
            String seccion = txt_idseccion.getText();
            mostrarlistado(curso,seccion);
    }//GEN-LAST:event_Btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnosSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnosSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnosSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoAlumnosSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoAlumnosSeccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ayuda;
    private javax.swing.JButton Btn_buscar;
    private javax.swing.JButton Btn_salir;
    private javax.swing.JLabel Lbl_idcurso;
    private javax.swing.JLabel Lbl_seccion;
    private javax.swing.JPanel Pnl_ListadoAlumnosSeccion;
    private javax.swing.JTable Tbl_listadoalumnosseccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_listado;
    private javax.swing.JTextField txt_idcurso;
    private javax.swing.JTextField txt_idseccion;
    // End of variables declaration//GEN-END:variables

}
